/* 
Programmed by: 	MAPA, Jamie Shekinah B. 	S14
Description: 	This program executes a one-player Pokemon game where user assembles 
				his own team of fighters and battles an enemy team generated by the program.
Last modified: 	December 3, 2018
Acknowledgements: 
	-stdio.h
	-stdlib.h
	-conio.h
	-string.h
*/

#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <string.h>
#define MAX 20
#define GRASS 0
#define FIRE 1
#define WATER 2

//made 'Name' a data type for strings
typedef char Name[MAX];

//function prototype for time
int time();


/*initialize function stores name, type, hp, and ap for each pokemon
@param (int) numPoke is the 
@param (Name) PokeName stores the name of the pokemon
@param (int) PokeType stores the type of the pokemon
@param (int) PokeHP stores the initial HP of the pokemon
@param (int) PokeAP stores the attack power of the pokemon
@return (void) no return value
*/
void init(int numPoke, Name PokeName, int *PokeType, int *PokeHP, int *PokeAP)
{

	switch(numPoke)
	{
		case 1:
			{
				strcpy(PokeName, "Bulbasaur");
				*PokeType = GRASS;
				*PokeHP = 160;
				*PokeAP = 40;
			} break;
		case 2:
			{
				strcpy(PokeName, "Bellsprout");
				*PokeType = GRASS;
				*PokeHP = 140;
				*PokeAP = 60;
			} break;
		case 3:
			{
				strcpy(PokeName, "Oddish");
				*PokeType = GRASS;
				*PokeHP = 150;
				*PokeAP = 50;
			} break;
		case 4:
			{
				strcpy(PokeName, "Charmander");
				*PokeType = FIRE;
				*PokeHP = 125;
				*PokeAP = 70;
			} break;
		case 5:
			{
				strcpy(PokeName, "Ninetails");
				*PokeType = FIRE;
				*PokeHP = 130;
				*PokeAP = 50;
			} break;
		case 6:
			{
				strcpy(PokeName, "Ponyta");
				*PokeType = FIRE;
				*PokeHP = 140;
				*PokeAP = 60;
			} break;
		case 7:
			{
				strcpy(PokeName, "Squirtle");
				*PokeType = WATER;
				*PokeHP = 180;
				*PokeAP = 20;
			} break;
		case 8:
			{
				strcpy(PokeName, "Psyduck");
				*PokeType = WATER;
				*PokeHP = 170;
				*PokeAP = 40;
			} break;
		case 9:
			{
				strcpy(PokeName, "Seel");
				*PokeType = WATER;
				*PokeHP = 150;
				*PokeAP = 50;
			} break;
		
	}
	
	
	
}


//displays start dialogue box
//@return (void) no return value
void press_start(){
	printf ("\n\n+-----------------------------------------------------------------+\n");
	printf ("|                                                                 |\n");
	printf ("|                      Let the games begin!                       |\n");
	printf ("|                                                                 |\n");
	printf ("+-----------------------------------------------------------------+\n");
}

/* this function is called when a pokemon has fainted and will be removed from the list of battling pokemon
@param (Name) PokeName[] is the list of names of chosen pokemons 
@param (int) PokeType[] is the list of types of chosen pokemons
@param (int) PokeHP[] is the list of HP of chosen pokemons
@param (int) PokeAP[] is the list of AP of chosen pokemons
@param (int) list_of_fighters[] is the list of the index from the original list of pokemons
@param (Name) fighter is the name of the current fighter that just fainted
@param (int) size is the number of the remaining pokemons on the list
@return (void) no return value
*/
void pokemon_fainted(Name PokeName[], int PokeType[], int PokeHP[], int PokeAP[], int list_of_fighters[], Name fighter, int *size)
{
	int i, index = 0;
	
	
	while(index < *size && (strcmp(fighter, PokeName[index])!=0))
		index++;
	
	
	for (i = index; i < (*size)-1; i++)
	{
		strcpy(PokeName[i], PokeName[i+1]);
		PokeType[i] = PokeType[i+1];
		PokeHP[i] = PokeHP[i+1];
		PokeAP[i] = PokeAP[i+1];
		list_of_fighters[i] = list_of_fighters[i+1];
	}
	
	(*size)--;
	
	
}

/* choose_fighter function displays team and asks player to choose which pokemon will fight first
@param (Name) PokeName[] is the list of names of the chosen pokemons 
@param (int) PokeType[] is the list of types of the chosen pokemons
@param (int) PokeHP[] is the list of HP of the chosen pokemons
@param (int) PokeAP[] is the list of AP of the chosen pokemons
@param (Name) scurrent_fighter is the name of the current fighter
@param (int) current_type is the type of the current fighter
@param (int) current_HP is the HP of the current fighter
@param (int) current_AP is the AP of the current fighter
@param (int) list_of_fighters[] is the list of index from the original list of pokemons
@param (int) size is the number of alive pokemons
@param (int) n is to distinguish whether the user or the enemy is choosing a fighter
@param (int) turn is used to execute the first turn differently
@return (void) no return value
*/
void choose_fighter(Name PokeName[], int PokeType[], int PokeHP[], int PokeAP[], Name scurrent_fighter, int *current_type, int *current_HP, int *current_AP, int list_of_fighters[], int size, int n, int turn){
		
		int num, i, temp, index=0;
		Name temp_fighter;
		int temp_type, temp_HP, temp_AP;
		if (size>0)
		{
			if (n == 0)
			{
				printf ("\n\n+-----------------------------------------------------------------+\n");
				printf ("|                                                                 |\n");
				printf ("|                       Choose fighter!                           |\n");
				printf ("|                                                                 |\n");
				printf ("+-----------------------------------------------------------------+\n\n");
				
				
				//called initialize function again to set the current fighter and its stats
				if (turn == 1)
				{
					for (i = 0; i < size; i++)
						printf ("\n\t%d. %s", i+1, PokeName[i]);
					
					printf("\n\tSend out which fighter:\t");
					scanf ("%d", &num);
					
					printf ("\n\t");				
					
					init (list_of_fighters[num-1], scurrent_fighter, current_type, current_HP, current_AP);
					pokemon_fainted(PokeName, PokeType, PokeHP, PokeAP, list_of_fighters, scurrent_fighter, &size);
					
				}
				else 
				{
					if (turn == 0)
					{
						for (i = 0; i < size; i++)
							printf ("\n\t%d. %s", i+1, PokeName[i]);
					}
					else
					{
						printf("\n\tCurrent in battle: %s\n\n", scurrent_fighter);
						for (i = 0; i < size-1; i++)
							printf ("\n\t%d. %s", i+1, PokeName[i]);
					}
					
					printf("\n\tSend out which fighter:\t");
					scanf ("%d", &num);
					
					printf ("\n\t");
					
					strcpy(temp_fighter, scurrent_fighter);
					temp_type = *current_type;
					temp_HP = *current_HP;
					temp_AP = *current_AP;
					
					strcpy(scurrent_fighter, PokeName[num-1]);
					*current_type = PokeType[num-1];
					*current_HP = PokeHP[num-1];
					*current_AP = PokeAP[num-1];
					
					strcpy(PokeName[num-1], temp_fighter);
					PokeType[num-1] = temp_type;
					PokeHP[num-1] = temp_HP;
					PokeAP[num-1] = temp_AP;
					
				}
				
				printf ("\tYou chose %s!\n\n", scurrent_fighter); 
				
				printf("\n\n");
			}
			
			
			// enemy choosing a fighter
			else if (n == 1)
			{
				
				if (turn == 1)
					{
						printf("\tList of Enemies:\n");
						for (i = 0; i < size; i++)
							printf ("\n\t%d. %s", i+1, PokeName[i]);
						
						srand(time(0));
						temp = size;
						num = rand() % temp;
						
						init (list_of_fighters[num], scurrent_fighter, current_type, current_HP, current_AP);
						pokemon_fainted(PokeName, PokeType, PokeHP, PokeAP, list_of_fighters, scurrent_fighter, &size);
						
					}
				else
				{
					printf("\tList of Enemies:\n");
					if (turn == 0)
					{
						for (i = 0; i < size; i++)
							printf ("\n\t%d. %s", i+1, PokeName[i]);
					}
					else
					{
						printf("\n\tCurrent in battle: %s\n\n", scurrent_fighter);
						for (i = 0; i < size-1; i++)
							printf ("\n\t%d. %s", i+1, PokeName[i]);
					}
						
					srand(time(0));
					temp = size;
					num = rand() % temp;
					index = 0;
					
					printf("\n\nSIZE: %d\n", size);
					//finds index
					while(index < size && (strcmp(scurrent_fighter, PokeName[index])!=0))
						index++;
					index--;
					
					//keep on finding a random number so that it won't switch on the same current fighter, except if it's the last fighter
					do
					{
						srand(time(0));
						temp = size;
						num = rand() % temp;
					} while (num == index);
					printf("\n\nRAND_INDEX = %d\n\n", num);
					if (num>=size)
						num--;
					strcpy(temp_fighter, scurrent_fighter);
					temp_type = *current_type;
					temp_HP = *current_HP;
					temp_AP = *current_AP;
					
					strcpy(scurrent_fighter, PokeName[num]);
					*current_type = PokeType[num];
					*current_HP = PokeHP[num];
					*current_AP = PokeAP[num];
					
					strcpy(PokeName[num], temp_fighter);
					PokeType[num] = temp_type;
					PokeHP[num] = temp_HP;
					PokeAP[num] = temp_AP;
				}	
				
				printf("\n\n\tEnemy chose %s\n\n", scurrent_fighter);
				printf("\n\n");
			}
			
		}
		
		
		
}

/*display_hp function displays fighter and enemy pokemon's current HP
@param (Name) fighter is the current fighter name
@param (Name) enemy is the current enemy name
@param (int) fighter_HP is the current fighter HP
@param (int) enemy_HP is the current enemy HP
@return (void) no return value 
*/
void display_hp (Name fighter, Name enemy, int fighter_HP, int enemy_HP){
	
	printf ("\n+-----------------------------+\t"); 		printf ("+-----------------------------+\n");
	printf ("|         %s             ",fighter); 			printf ("|         %s                \n",enemy);
	printf ("|         HP: %d            \t",fighter_HP);   printf ("|         HP: %d            \n",enemy_HP);
	printf ("+-----------------------------+\t");			printf ("+-----------------------------+\n");
	
	
	
	
}

/* compute_effectiveness computes for the effectiveness of the attack of a pokemon
@param (int) type is the type of the offending pokemon
@param (int) enemyType is the type of the defending pokemon
@return (float) returns a float value which multiplies the power of the attack if it's effective
*/
float compute_effectiveness(int type, int enemyType)
{
	if (type == GRASS && enemyType == WATER) return 1.5;
	else if (type == WATER && enemyType == FIRE) return 1.5;
	else if (type == FIRE && enemyType == GRASS) return 1.5;
	else return 1;
	
}


/* did_it_hit determines if the attack of the pokemon hit
@param (int) move is the attack made by the pokemon
@param (int) type is the type of the pokemon who made the attack
@return (int) hit returns an int value which determines if it hit or not
*/
int did_it_hit(int move, int *type)
{
	int hit = 1, accuracy;
	
	srand(time(0));
	accuracy = rand() % 100 + 1;
	
	switch(*type)
	{
		case GRASS: 
			{
				switch(move)	
					{
						case 1: 
							{
								if (accuracy >= 90)
									hit = 0;
							} break;
						case 2: hit = 1; break;
						case 3: 
							{
								if (accuracy >= 95)
									hit = 0;
							} break;
				}
			} break;
		case FIRE: 
			{
				switch(move)
					{
						case 1: hit = 1; break;
						case 2: 
							{
								if (accuracy >= 80)
									hit = 0;
							} break;
						case 3:
							{
								if (accuracy >= 90)
									hit = 0;
							} break;
					}
			} break;
		case WATER: 
			{
				switch(move)	
				{
					case 1: hit = 1; break;
					case 2: 
						{
							if (accuracy >= 30)
								hit = 0;
						} break;
					case 3:
						{
							if (accuracy >= 90)
								hit = 0;
						} break;
				}
			} break;
	}
	
	return hit;
}

/* generate_rand_A generates a random number between the attack power and the power point
@param (int) AP is the AP of the pokemon
@param (int) PP is the PP of its attack
@return (int) A is the returned value is the random number generated
*/
int generate_rand_A(int AP, int PP)
{
	int A = NULL, num;
	while (A == NULL)
	{
		srand(time(0));
		num = rand()%PP + 1;
		if (num >= AP)
			A = num;
	}

	return A;
}

/* compute_A computes for A for the damage calculation
@param (int) AP is the AP of the pokemon
@param (int) move is the move done by the pokemon
@param (int) type is the type of the pokemon
@return (int) A is the returned value that is used to compute for the damage
*/
int compute_A(int *AP, int move, int *type)
{
	int A;
	
	
	switch(*type)
	{
		case GRASS: 
		{
			switch(move)	
			{
				case 1: 
					{
						if (*AP < 130)
							A = generate_rand_A(*AP, 130);
						else if (*AP == 130)
							A = *AP;
						else
							A = generate_rand_A(130, *AP);
							
					} break;
				case 2: 
					{
						if (*AP < 50)
							A = generate_rand_A(*AP, 50);
						else if (*AP == 50)
							A = *AP;
						else
							A = generate_rand_A(50, *AP);
					}break;
				case 3: 
					{
						if (*AP < 55)
							A = generate_rand_A(*AP, 55);
						else if (*AP == 55)
							A = *AP;
						else
							A = generate_rand_A(55, *AP);
					} break;
			}
		} break;
		
		case FIRE: 
			{
				switch(move)
					{
						case 1:
							{
								if (*AP < 60)
									A = generate_rand_A(*AP, 60);
								else if (*AP == 60)
									A = *AP;
								else
									A = generate_rand_A(60, *AP);
							} break;
						case 2: 
							{
								if (*AP < 85)
									A = generate_rand_A(*AP, 85);
								else if (*AP == 85)
									A = *AP;
								else
									A = generate_rand_A(85, *AP);
							} break;
						case 3:
							{
								if (*AP < 70)
									A = generate_rand_A(*AP, 70);
								else if (*AP == 70)
									A = *AP;
								else
									A = generate_rand_A(70, *AP);
							} break;
					}
			} break;
		case WATER: 
			{
				switch(move)	
				{
					case 1:
						{
							if (*AP < 40)
								A = generate_rand_A(*AP, 40);
							else if (*AP == 40)
								A = *AP;
							else
								A = generate_rand_A(40, *AP);
						} break;
					case 2: 
						{
							if (*AP < 185)
								A = generate_rand_A(*AP, 185);
							else if (*AP == 185)
								A = *AP;
							else
								A = generate_rand_A(185, *AP);
						} break;
					case 3:
						{
							if (*AP < 70)
								A = generate_rand_A(*AP, 70);
							else if (*AP == 70)
								A = *AP;
							else
								A = generate_rand_A(70, *AP);
						} break;
				}
			} break;
	}
	
	
	
	return A;
}

/* turn_attack is called when the user chooses attack, returns which move has been used
@param (Name) PokeName is the name of the pokemon
@param (int) PokeType is the type of the attacking pokemon
@param (int) n determines whether the fighter or the enemy is attacking
@return (int) move is the returned value that determines which move has been used
*/ 
int turn_attack(Name PokeName, int PokeType, int n){
	
	int move; 
	
	
	switch (PokeType)
	{
		case GRASS: 
			{
				printf("\n\t1. Leaf Storm\n");
				printf("\t2. Mega Drain\n");
				printf("\t3. Razor Leaf\n");
			}
			break;
		case FIRE: 
			{
				printf("\n\t1. Ember\n");
				printf("\t2. Fire Punch\n");
				printf("\t3. Flame Wheel\n");
			} break;
		case WATER: 
			{
				printf("\n\t1. Bubble\n");
				printf("\t2. Hydro Pump\n");
				printf("\t3. Surf\n");
			} break;
		
	}
	if (n == 0)
	{
		printf ("\n\tSelect an attack: ");
		scanf("%d", &move);
	}
	else
	{
		move = rand() % 3 + 1;
	}
	
	switch (PokeType)
	{
		case GRASS: 
			{
				switch(move)
				{
					case 1: printf("\n\t%s Used Leaf Storm\n", PokeName); break;
					case 2: printf("\n\t%s Used Mega Drain\n", PokeName); break;
					case 3: printf("\n\t%s Used Razor Leaf\n", PokeName); break;
				}
			}
			break;
		case FIRE: 
			{
				switch(move)
				{
					case 1: printf("\n\t%s Used Ember\n", PokeName); break;
					case 2: printf("\n\t%s Used Fire Punch\n", PokeName); break;
					case 3: printf("\n\t%s Used Flame Wheel\n", PokeName); break;
				}
			} break;
		case WATER: 
			{
				switch(move)
				{
					case 1: printf("\n\t%s Used Bubble\n", PokeName); break;
					case 2: printf("\n\t%s Used Hydro Pump\n", PokeName); break;
					case 3: printf("\n\t%s Used Surf\n", PokeName); break;
				}
				
			} break;
		
	}
	return move;
	
}

//turn_potion function adds 20 HP to the pokemon's current HP
//@return (int) returns 20 for the HP
int turn_potion(){
	return 20;
}



/* pokemon_main function prints the list of pokemon the player can choose from, 
allows the user to select fighters, and prints player's selected team
@param (Name) PokeName[] is the list of names of the user's chosen pokemons 
@param (Name) eNAMEy[] is the list of names of the chosen enemy pokemons
@param (int) PokeType[] is the list of types of the chosen pokemons
@param (int) PokeHP[] is the list of HP of the chosen pokemons
@param (int) PokeAP[] is the list of AP of the chosen pokemons
@param (int) enemy_type[] is the list of types of the enemy pokemons
@param (int) enemy_HP[] is the list of HPs of each enemy pokemon
@param (int) enemy_AP[] is the list of APs of each enemy pokemon
@param (Name) player_name is the player's name
@param (Name) enemy_name is the enemy's name
@param (int) list_of_fighters[] is the list of index of the user from the original list of pokemons
@param (int) list_of_enemies[] is the list of index of the enemy from the original list of pokemons
@param (Name) scurrent_fighter is the name of the current fighter
@param (Name) scurrent_enemy is the name of the current enemy fighter
@param (int) current_type is the type of the current fighter
@param (int) current_enemyType is the type of the current enemy fighter
@param (int) current_HP is the HP of the current fighter
@param (int) current_enemyHP is the HP of the current enemy fighter
@param (int) current_AP is the AP of the current fighter
@param (int) current_enemyAP is the AP of the current enemy fighter
@return (void) no return value

*/
void pokemon_main(Name PokeName[], Name eNAMEy[], int PokeType[], int PokeHP[], int PokeAP[], int enemy_type[], int enemy_HP[], int enemy_AP[], Name *player_name, Name *enemy_name, int list_of_fighters[], int list_of_enemies[],
				Name scurrent_fighter, Name scurrent_enemy, int *current_type, int *current_enemyType, int *current_HP, int *current_enemyHP, int *current_AP, int *current_enemyAP){
	
	int i;
	

	
	
	printf ("+-----------------------------------------------------------------+\n");
	printf ("|                                                                 |\n");
	printf ("|                   Welcome to Pokemon Showdown!                  |\n");
	printf ("|                                                                 |\n");
	printf ("+-----------------------------------------------------------------+\n");	
		printf ("\n\tInput player name: ");
			scanf ("%s", *player_name);
		printf ("\tInput enemy name: ");
			scanf ("%s", *enemy_name);
		printf ("\n\tHello %s! ", *player_name);
		printf ("Are you ready to fight %s?\n", *enemy_name);
	
	
	
	printf ("\n+-----------------------------------------------------------------+\n");
	printf ("|                                                                 |\n");
	printf ("|                       Assemble your team!                       |\n");
	printf ("|                                                                 |\n");
	printf ("+-----------------------------------------------------------------+\n\n");
	printf ("\tChoose (3) fighters:\n");
	printf ("\t   1.  Bulbasaur \n");		//grass
	printf ("\t   2.  Bellsprout \n");
	printf ("\t   3.  Oddish \n");
	printf ("\t   4.  Charmander \n");	//fire
	printf ("\t   5.  Ninetales \n");
	printf ("\t   6.  Ponyta \n");	
	printf ("\t   7.  Squirtle \n");	//water
	printf ("\t   8.  Psyduck \n");
	printf ("\t   9.  Seel \n\n");


	for(i = 0; i < 3; i++)
	{
		printf ("\tChoose fighter %d:\t", i+1);
		scanf ("%d", &list_of_fighters[i]);
		
	}
	
	printf ("\n\t");	
	
	for (i = 0; i < 3; i++)
	{
		
		switch (list_of_fighters[i])
		{	case 1 : printf ("%s chose Bulbasaur\n", *player_name); break;
			case 2 : printf ("%s chose Bellsprout \n", *player_name); break;
			case 3 : printf ("%s chose Oddish \n", *player_name); break;
			case 4 : printf ("%s chose Charmander \n", *player_name); break;
			case 5 : printf ("%s chose Ninetales \n", *player_name); break;
			case 6 : printf ("%s chose Ponyta \n", *player_name); break;
			case 7 : printf ("%s chose Squirtle \n", *player_name); break;
			case 8 : printf ("%s chose Psyduck \n", *player_name); break;
			case 9 : printf ("%s chose Seel \n", *player_name); break;
		}
		
		init(list_of_fighters[i], PokeName[i], &PokeType[i], &PokeHP[i], &PokeAP[i]);
		
		printf("\t");
			
	}

	
	i=0;
	int j;
	int num = 0;
	int chosen;
	printf("\n\n");
	
	
	// CPU CHOOSING ITS TEAM
	for (j = 0; j < 3; j++)
	{
		srand(time(0));
		num = rand() % 9 + 1;
		chosen = 0;
			
		for (i=0; i<3; i++)
		{
			if (list_of_fighters[i] == num || list_of_enemies[i] == num)
				chosen = 1;
		}
		if (chosen == 0)
		{	list_of_enemies[j] = num;
			
			switch (list_of_enemies[j])
			{	case 1 : printf ("\t%s chose Bulbasaur\n", *enemy_name); break;
				case 2 : printf ("\t%s chose Bellsprout \n", *enemy_name); break;
				case 3 : printf ("\t%s chose Oddish \n", *enemy_name); break;
				case 4 : printf ("\t%s chose Charmander \n", *enemy_name); break;
				case 5 : printf ("\t%s chose Ninetales \n", *enemy_name); break;
				case 6 : printf ("\t%s chose Ponyta \n", *enemy_name); break;
				case 7 : printf ("\t%s chose Squirtle \n", *enemy_name); break;
				case 8 : printf ("\t%s chose Psyduck \n", *enemy_name); break;
				case 9 : printf ("\t%s chose Seel \n", *enemy_name); break;		
			}
			init(list_of_enemies[j], eNAMEy[j], &enemy_type[j], &enemy_HP[j], &enemy_AP[j]);
		}
		
		else if (chosen == 1)
			j--;
		
	}
		
	
	printf ("\n\tYour team is all set. Let's go!\n\n");
	
	
	choose_fighter(PokeName, PokeType, PokeHP, PokeAP, scurrent_fighter, current_type, current_HP, current_AP, list_of_fighters, 3, 0, 1);
	choose_fighter(eNAMEy, enemy_type, enemy_HP, enemy_AP, scurrent_enemy, current_enemyType, current_enemyHP, current_enemyAP, list_of_enemies, 3, 1, 1);
	

}



/* turn function displays player action dialogue box and asks for player's next action
@param (Name) PokeName[] is the list of names of the user's chosen pokemons 
@param (int) PokeType[] is the list of types of the chosen pokemons
@param (int) PokeHP[] is the list of HP of the chosen pokemons
@param (int) PokeAP[] is the list of AP of the chosen pokemons
@param (int) list_of_fighters[] is the list of index of the user from the original list of pokemons
@param (Name) scurrent_fighter is the name of the current fighter
@param (int) current_type is the type of the current fighter
@param (int) current_enemyType is the type of the current enemy fighter
@param (int) current_HP is the HP of the current fighter
@param (int) current_enemyHP is the HP of the current enemy fighter
@param (int) current_AP is the AP of the current fighter
@param (int) size is the number of alive pokemons
@return (void) no return value

*/
void turn (int *current_enemyHP, int *current_enemyType, Name PokeName[], int PokeType[], int PokeHP[], int PokeAP[], Name scurrent_fighter, 
			int *current_type, int *current_HP, int *current_AP, int list_of_fighters[], int *size ){
	int turn, move, damage;
	printf ("\n\n+-----------------------------------------------------------------+\n");
	printf ("|                                                                 |\n");
	printf ("|\tIt's your turn! What will you do?                         |\n");
	printf ("|                                                                 |\n");
	printf ("|\tPress:\t1 - attack\t2 - potion\t3 - switch        |\n");
	printf ("|                                                                 |\n");
	printf ("+-----------------------------------------------------------------+\n");
	scanf ("%d",&turn);
		switch (turn)
		{	case 1 : 
				{
					
					move = turn_attack(scurrent_fighter, *current_type, 0); 
					
					damage = compute_A(current_AP, move, current_type) * did_it_hit(move, current_type) * compute_effectiveness(*current_type, *current_enemyType);
					*current_enemyHP -= damage;
					
					if (damage > 0)
						printf("\n\t%s inflicted %d Damage!\n", scurrent_fighter, damage);
					else
						printf("\n\tThe move missed!");
						
					
					if (compute_effectiveness(*current_type, *current_enemyType) == 1.5 && damage>0)
						printf("\n\tIt's Super Effective!\n");
					
					if (*current_enemyHP < 0)
						*current_enemyHP = 0;
					
				} break;
			case 2 : *current_HP += turn_potion(); break;
			case 3 : choose_fighter(PokeName, PokeType, PokeHP, PokeAP, scurrent_fighter, current_type, current_HP, current_AP, list_of_fighters, *size, 0, 69); break;
				
		}
}

/*
separate turn func for computer (rand)
turn_enemy function generates a random turn for enemy team
@param (Name) eNAMEy[] is the list of names of the user's chosen pokemons 
@param (int) enemy_type[] is the list of types of the chosen pokemons
@param (int) enemuy_HP[] is the list of HP of the chosen pokemons
@param (int) enemy_AP[] is the list of AP of the chosen pokemons
@param (int) list_of_enemies[] is the list of index of the user from the original list of pokemons
@param (Name) scurrent_fighter is the name of the current fighter
@param (int) current_type is the type of the current fighter
@param (int) current_enemyType is the type of the current enemy fighter
@param (int) current_HP is the HP of the current fighter
@param (int) current_enemyHP is the HP of the current enemy fighter
@param (int) current_enemyAP is the AP of the current fighter
@param (int) size is the number of alive pokemons
@return (void) no return value
*/
void turn_enemy(int *current_HP, int *current_type, Name eNAMEy[], int enemy_type[], int enemy_HP[], int enemy_AP[], Name scurrent_enemy, int *current_enemyType, int *current_enemyHP, int *current_enemyAP, int list_of_enemies[], int *size){
	
	int turn, move, damage;
	
	//enemy rand attack generator
	
		turn = rand() % 6;
		//+20HP to current enemy pokemon
		if (turn == 1)
		{
			printf ("\n\tEnemy chose to use potion!\n"); 
			*current_enemyHP += turn_potion();
		}
		//enemy chooses to switch fighter
		else if (turn == 2)
		{
			printf ("\n\tEnemy chose to switch pokemon!\n"); 
			choose_fighter(eNAMEy, enemy_type, enemy_HP, enemy_AP, scurrent_enemy, current_enemyType, current_enemyHP, current_enemyAP, list_of_enemies, *size, 1, 69);
		}
		//rand attack
		else
		{
			printf ("\n\tEnemy chose to attack!\n\n");
			move = turn_attack(scurrent_enemy, *current_enemyType, 1);
			
			damage = compute_A(current_enemyAP, move, current_enemyType) * did_it_hit(move, current_enemyType) * compute_effectiveness(*current_enemyType, *current_type);
			*current_HP -= damage;
	
			if (damage > 0)
				printf("\n\t%s inflicted %d Damage!\n", scurrent_enemy, damage);
			else
				printf("\n\tThe move missed!");
			
			if (compute_effectiveness(*current_enemyType, *current_type) == 1.5 && damage>0)
				printf("\n\tIt's Super Effective!\n");
	
			if (*current_HP < 0)
				*current_HP = 0;
			
		}
		
}

/* round function executes diplay_hp and turn functions 
allows the user to select fighters, and prints player's selected team
@param (Name) PokeName[] is the list of names of the user's chosen pokemons 
@param (Name) eNAMEy[] is the list of names of the chosen enemy pokemons
@param (int) PokeType[] is the list of types of the chosen pokemons
@param (int) PokeHP[] is the list of HP of the chosen pokemons
@param (int) PokeAP[] is the list of AP of the chosen pokemons
@param (int) enemy_type[] is the list of types of the enemy pokemons
@param (int) enemy_HP[] is the list of HPs of each enemy pokemon
@param (int) enemy_AP[] is the list of APs of each enemy pokemon
@param (Name) player_name is the player's name
@param (Name) enemy_name is the enemy's name
@param (int) list_of_fighters[] is the list of index of the user from the original list of pokemons
@param (int) list_of_enemies[] is the list of index of the enemy from the original list of pokemons
@param (Name) scurrent_fighter is the name of the current fighter
@param (Name) scurrent_enemy is the name of the current enemy fighter
@param (int) current_type is the type of the current fighter
@param (int) current_enemyType is the type of the current enemy fighter
@param (int) current_HP is the HP of the current fighter
@param (int) current_enemyHP is the HP of the current enemy fighter
@param (int) current_AP is the AP of the current fighter
@param (int) current_enemyAP is the AP of the current enemy fighter
@param (int) PokeSize is the number of alive fighters
@param (int) EneSize is number of alive enemy fighters
@param (Name) winner is the player that will win
@return (void) no return value

*/

void round (Name PokeName[], Name eNAMEy[], int PokeType[], int PokeHP[], int PokeAP[], int enemy_type[], int enemy_HP[], int enemy_AP[], Name *player_name, Name *enemy_name, 
				int list_of_fighters[], int list_of_enemies[], Name scurrent_fighter, Name scurrent_enemy, int *current_type, int *current_enemyType, int *current_HP, int *current_enemyHP, 
				int *current_AP, int *current_enemyAP, int *PokeSize, int *EneSize, Name *winner){
		int i;
		
		int all_dead = 0, counter = 1;
		while( (*current_HP > 0 || *current_enemyHP > 0) && all_dead == 0)
		{	
			display_hp (scurrent_fighter, scurrent_enemy, *current_HP, *current_enemyHP);
			printf("\n\n\tTurn %d", counter);
			
			
			//user's turn
			if (counter % 2 == 1)
			{
				turn (current_enemyHP, current_enemyType, PokeName, PokeType, PokeHP, PokeAP, scurrent_fighter, current_type, current_HP, current_AP, list_of_fighters, PokeSize);
			}
			
			//CPU's turn
			else if (counter % 2 == 0)
			{
				turn_enemy(current_HP, current_type, eNAMEy, enemy_type, enemy_HP, enemy_AP, scurrent_enemy, current_enemyType, current_enemyHP, current_enemyAP, list_of_enemies, EneSize);
			}
			
			//when a pokemon faints
			if (*current_HP == 0 || *current_enemyHP == 0)
			{
				if (PokeSize > 0 || EneSize > 0)
				{
					if (*current_HP == 0)
						{
							printf("\n\t%s has fainted!\n", scurrent_fighter);
							pokemon_fainted(PokeName, PokeType, PokeHP, PokeAP, list_of_fighters, scurrent_fighter, PokeSize);
							choose_fighter(PokeName, PokeType, PokeHP, PokeAP, scurrent_fighter, current_type, current_HP, current_AP, list_of_fighters, *PokeSize, 0, 1);
						}
					else if (*current_enemyHP == 0)
						{
							printf("\n\t%s has fainted!\n", scurrent_enemy);
							pokemon_fainted(eNAMEy, enemy_type, enemy_HP, enemy_AP, list_of_enemies, scurrent_enemy, EneSize);
							choose_fighter(eNAMEy, enemy_type, enemy_HP, enemy_AP, scurrent_enemy, current_enemyType, current_enemyHP, current_enemyAP, list_of_enemies, *EneSize, 1, 1);
						}
				}
			}
			printf("\n\n\tEnemies left: %d", *EneSize);
			if (*PokeSize==0 || *EneSize==0)
				all_dead = 1;

			counter++;
		}
		
		if (*EneSize == 0)
			strcpy(*winner, *player_name);
		else
			strcpy(*winner, *enemy_name);
		
}


/* game_over function displays game over dialogue box and declares the winner once all pokemon of defeated team has 0 HP
@param (Name) winner is the winner of the game
@return (void) returns no value
*/
void game_over (Name winner){
	
	
		printf ("\n+-----------------------------------------------------------------+\n");
		printf ("|                                                                 |\n");
		printf ("|                            Game Over                            |\n");
		printf ("|                                                                 |\n");
		printf ("+-----------------------------------------------------------------+\n");	
		
		printf ("\n\t%s is the winner!\n\n",winner);
			
	
}


/* play_again function asks if user wants to play again, then restarts game if player says chooses yes and thanks user for playing if no
@return (void) returns no value
*/
void play_again (){
	int play;
		printf ("/n+-----------------------------------------------------------------+\n");
		printf ("|                                                                 |\n");
		printf ("|            That was fun! Do you want to play again?             |\n");
		printf ("|                                                                 |\n");
		printf ("+-----------------------------------------------------------------+\n");
		printf ("\n\t\t 1 - yes\t0 - no\n");
		scanf ("%d",&play);
	if (play==1)
		{
			main();
		}
	else if (play==0)
		{	printf ("\n+-----------------------------------------------------------------+\n");
			printf ("|                                                                 |\n");
			printf ("|                  Okay. Thank you for playing!                   |\n");
			printf ("|                                                                 |\n");
			printf ("+-----------------------------------------------------------------+\n");
		}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

int main (){
	Name PokeName[3], eNAMEy[3];
	int PokeType[3], PokeHP[3], PokeAP[3], enemy_type[3], enemy_HP[3], enemy_AP[3];
	
	Name player_name, enemy_name, winner;
	
	int list_of_fighters[3];
	int list_of_enemies[3];
	
// array size of the list of alive pokemons
	int PokeSize = 3, EneSize = 3;

// current pokemon that's on the battle field
	Name scurrent_fighter, scurrent_enemy; 
//set to null for the switching of fighters, for checking

	int current_type, current_HP = NULL, current_AP;
	int current_enemyType, current_enemyHP = NULL, current_enemyAP;



	pokemon_main (PokeName, eNAMEy, PokeType, PokeHP, PokeAP, enemy_type, enemy_HP, enemy_AP, &player_name, &enemy_name, list_of_fighters, list_of_enemies,
					scurrent_fighter, scurrent_enemy, &current_type, &current_enemyType, &current_HP, &current_enemyHP, &current_AP, &current_enemyAP);
	press_start ();
	printf("Main pokesize = %d\n", PokeSize);
	round (PokeName, eNAMEy, PokeType, PokeHP, PokeAP, enemy_type, enemy_HP, enemy_AP, &player_name, &enemy_name, list_of_fighters, list_of_enemies, scurrent_fighter, scurrent_enemy, 
			&current_type, &current_enemyType, &current_HP, &current_enemyHP, &current_AP, &current_enemyAP, &PokeSize, &EneSize, &winner);
	game_over(winner);
	play_again ();
	
	return 0;
}
